In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Se carga el archivo csv

In [2]:
amazon_prime_tittles = pd.read_csv("amazon_prime_titles-score.csv")

Se observa la informacion que contiene el csv

In [3]:
amazon_prime_tittles.info

<bound method DataFrame.info of      show_id     type                    title         director  \
0         s1    Movie      The Grand Seduction     Don McKellar
1         s2    Movie     Take Care Good Night     Girish Joshi
2         s3    Movie     Secrets of Deception      Josh Webber
3         s4    Movie       Pink: Staying True   Sonia Anderson
4         s5    Movie            Monster Maker     Giles Foster
...      ...      ...                      ...              ...
9663   s9664    Movie      Pride Of The Bowery  Joseph H. Lewis
9664   s9665  TV Show            Planet Patrol              NaN
9665   s9666    Movie                  Outpost     Steve Barker
9666   s9667  TV Show  Maradona: Blessed Dream              NaN
9667   s9668    Movie              Harry Brown    Daniel Barber

                                                   cast         country  \
0        Brendan Gleeson, Taylor Kitsch, Gordon Pinsent          Canada
1      Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar           India
2     Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...   United States
3     Interviews with: Pink, Adele, Beyoncé, Britney...   United States
4     Harry Dean Stanton, Kieran O'Brien, George Cos...  United Kingdom
...                                                 ...             ...
9663                           Leo Gorcey, Bobby Jordan             NaN
9664  DICK VOSBURGH, RONNIE STEVENS, LIBBY MORRIS, M...             NaN
9665  Ray Stevenson, Julian Wadham, Richard Brake, M...             NaN
9666  Esteban Recagno, Ezequiel Stremiz, Luciano Vit...             NaN
9667  Michael Caine, Emily Mortimer, Joseph Gilgun, ...             NaN

          date_added  release_year rating   duration                listed_in  \
0     March 30, 2021          2014    NaN    113 min            Comedy, Drama
1     March 30, 2021          2018    13+    110 min     Drama, International
2     March 30, 2021          2017    NaN     74 min  Action, Drama, Suspense
3     March 30, 2021          2014    NaN     69 min              Documentary
4     March 30, 2021          1989    NaN     45 min           Drama, Fantasy
...              ...           ...    ...        ...                      ...
9663             NaN          1940     7+     60 min                   Comedy
9664             NaN          2018    13+  4 Seasons                 TV Shows
9665             NaN          2008      R     90 min                   Action
9666             NaN          2021  TV-MA   1 Season            Drama, Sports
9667             NaN          2010      R    103 min  Action, Drama, Suspense

                                            description  score
0     A small fishing village must procure a local d...     99
1     A Metro Family decides to fight a Cyber Crimin...     37
2     After a man discovers his wife is cheating on ...     20
3     Pink breaks the mold once again, bringing her ...     27
4     Teenage Matt Banting wants to work with a famo...     75
...                                                 ...    ...
9663  New York City street principles get an East Si...      7
9664  This is Earth, 2100AD - and these are the adve...     49
9665  In war-torn Eastern Europe, a world-weary grou...     68
9666  The series tells the story of Diego Maradona, ...     72
9667  Harry Brown, starring two-time Academy Award w...     30

[9668 rows x 13 columns]>

Se crea una columna llamada "id", la cual contiene la letra inicial de la plataforma junto con el "show id". Por ejemplo la plataforma Amazon y el show id s1, la columna id sería igual a as1.

In [4]:
amazon_prime_tittles["id"] = "a" + amazon_prime_tittles["show_id"]

In [5]:
amazon_prime_tittles.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,score,id
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...,99,as1
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...,37,as2
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...,20,as3
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ...",27,as4
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...,75,as5

Todos los valores nulos de la columna  rating se renombran con la letra "G"

In [6]:
amazon_prime_tittles["rating"].fillna("G", inplace = True)

Se convierten en minusculas todas las palabras contenidas en las columnas: type, title, director, cast, country, date addes, listed in, description.

In [7]:
amazon_prime_tittles["type"] = amazon_prime_tittles["type"].str.lower()
amazon_prime_tittles["title"] = amazon_prime_tittles["title"].str.lower()
amazon_prime_tittles["director"] = amazon_prime_tittles["director"].str.lower()
amazon_prime_tittles["cast"] = amazon_prime_tittles["cast"].str.lower()
amazon_prime_tittles["country"] = amazon_prime_tittles["country"].str.lower()
amazon_prime_tittles["date_added"] = amazon_prime_tittles["date_added"].str.lower()
amazon_prime_tittles["listed_in"] = amazon_prime_tittles["listed_in"].str.lower()
amazon_prime_tittles["description"] = amazon_prime_tittles["description"].str.lower()

Se separan en 2 la columna duration. Por un lado una columna contiene el tipo de dato (min, sesion) y por otro lado el numero asociado a la duracion

In [8]:
name=amazon_prime_tittles["duration"].str.split(expand=True)
name.columns=["duration_int", "duration_type"]
amazon_prime_tittles=pd.concat([amazon_prime_tittles, name], axis=1)

Se eliminda la columna duracion, pues ya quedo separada

In [9]:
amazon_prime_tittles.drop(["duration"], axis=1)

,show_id,type,title,director,cast,country,date_added,release_year,rating,listed_in,description,score,id,duration_int,duration_type
0,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,"march 30, 2021",2014,G,"comedy, drama",a small fishing village must procure a local d...,99,as1,113,min
1,s2,movie,take care good night,girish joshi,"mahesh manjrekar, abhay mahajan, sachin khedekar",india,"march 30, 2021",2018,13+,"drama, international",a metro family decides to fight a cyber crimin...,37,as2,110,min
2,s3,movie,secrets of deception,josh webber,"tom sizemore, lorenzo lamas, robert lasardo, r...",united states,"march 30, 2021",2017,G,"action, drama, suspense",after a man discovers his wife is cheating on ...,20,as3,74,min
3,s4,movie,pink: staying true,sonia anderson,"interviews with: pink, adele, beyoncé, britney...",united states,"march 30, 2021",2014,G,documentary,"pink breaks the mold once again, bringing her ...",27,as4,69,min
4,s5,movie,monster maker,giles foster,"harry dean stanton, kieran o'brien, george cos...",united kingdom,"march 30, 2021",1989,G,"drama, fantasy",teenage matt banting wants to work with a famo...,75,as5,45,min
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9663,s9664,movie,pride of the bowery,joseph h. lewis,"leo gorcey, bobby jordan",NaN,NaN,1940,7+,comedy,new york city street principles get an east si...,7,as9664,60,min
9664,s9665,tv show,planet patrol,NaN,"dick vosburgh, ronnie stevens, libby morris, m...",NaN,NaN,2018,13+,tv shows,"this is earth, 2100ad - and these are the adve...",49,as9665,4,Seasons
9665,s9666,movie,outpost,steve barker,"ray stevenson, julian wadham, richard brake, m...",NaN,NaN,2008,R,action,"in war-torn eastern europe, a world-weary grou...",68,as9666,90,min
9666,s9667,tv show,maradona: blessed dream,NaN,"esteban recagno, ezequiel stremiz, luciano vit...",NaN,NaN,2021,TV-MA,"drama, sports","the series tells the story of diego maradona, ...",72,as9667,1,Season
9667,s9668,movie,harry brown,daniel barber,"michael caine, emily mortimer, joseph gilgun, ...",NaN,NaN,2010,R,"action, drama, suspense","harry brown, starring two-time academy award w...",30,as9668,103,min

Se cambia el formato de la columna date added al formato año/mes/dia

In [10]:
amazon_prime_tittles["date_added"] = pd.to_datetime(amazon_prime_tittles["date_added"])

Se crea la columna respectiva para cada platafomra

In [11]:
amazon_prime_tittles["Plataforma"] = "amazon"

ETL del csv netflix

In [12]:
netflix_titles =pd.read_csv("netflix_titles-score.csv")
netflix_titles["id"] = "a" + netflix_titles["show_id"]
netflix_titles["rating"].fillna("G", inplace = True)

netflix_titles["type"] = netflix_titles["type"].str.lower()
netflix_titles["title"] = netflix_titles["title"].str.lower()
netflix_titles["director"] = netflix_titles["director"].str.lower()
netflix_titles["cast"] = netflix_titles["cast"].str.lower()
netflix_titles["country"] = netflix_titles["country"].str.lower()
netflix_titles["date_added"] = netflix_titles["date_added"].str.lower()
netflix_titles["listed_in"] = netflix_titles["listed_in"].str.lower()
netflix_titles["description"] = netflix_titles["description"].str.lower()

name=netflix_titles["duration"].str.split(expand=True)
name.columns=["duration_int", "duration_type"]
netflix_titles=pd.concat([netflix_titles, name], axis=1)
netflix_titles.drop(["duration"], axis=1)
netflix_titles["date_added"] = pd.to_datetime(netflix_titles["date_added"])
netflix_titles["Plataforma"] = "netflix"

ETL del csv Disney

In [13]:
disney_plus_titles = pd.read_csv("disney_plus_titles-score.csv")

disney_plus_titles["id"] = "d" + disney_plus_titles["show_id"]
disney_plus_titles["rating"].fillna("G", inplace = True)

disney_plus_titles["type"] = disney_plus_titles["type"].str.lower()
disney_plus_titles["title"] = disney_plus_titles["title"].str.lower()
disney_plus_titles["director"] = disney_plus_titles["director"].str.lower()
disney_plus_titles["cast"] = disney_plus_titles["cast"].str.lower()
disney_plus_titles["country"] = disney_plus_titles["country"].str.lower()
disney_plus_titles["date_added"] = disney_plus_titles["date_added"].str.lower()
disney_plus_titles["listed_in"] = disney_plus_titles["listed_in"].str.lower()
disney_plus_titles["description"] = disney_plus_titles["description"].str.lower()

name=disney_plus_titles["duration"].str.split(expand=True)
name.columns=["duration_int", "duration_type"]
disney_plus_titles=pd.concat([disney_plus_titles, name], axis=1)

disney_plus_titles.drop(["duration"], axis=1)

disney_plus_titles["date_added"] = pd.to_datetime(disney_plus_titles["date_added"])
disney_plus_titles["Plataforma"] = "disney"

ETL del csv Hulu

In [31]:
hulu_titles = pd.read_csv("hulu_titles-score (2).csv")

In [32]:
hulu_titles["id"] = "h" + hulu_titles["show_id"]
hulu_titles["rating"].fillna("G", inplace = True)
hulu_titles["type"] = hulu_titles["type"].str.lower()
hulu_titles["title"] = hulu_titles["title"].str.lower()
hulu_titles["director"] = hulu_titles["director"].str.lower()
#hulu_titles["cast"].str.lower()
hulu_titles["country"] = hulu_titles["country"].str.lower()
hulu_titles["date_added"] = hulu_titles["date_added"].str.lower()
hulu_titles["listed_in"] = hulu_titles["listed_in"].str.lower()
hulu_titles["description"] = hulu_titles["description"].str.lower()

name= hulu_titles["duration"].str.split(expand=True)
name.columns=["duration_int", "duration_type"]
hulu_titles=pd.concat([hulu_titles, name], axis=1)
hulu_titles.drop(["duration"], axis=1)

hulu_titles["date_added"] = pd.to_datetime(hulu_titles["date_added"])
hulu_titles["Plataforma"] = "hulu"

Se juntan todos los archivos csv despues de realizarles a cada uno un ETL, en un solo archivo que contenga toda la información, para posterior uso de la data

In [33]:
bases_datos = pd.concat([amazon_prime_tittles, disney_plus_titles, netflix_titles, hulu_titles])
bases_datos

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,score,id,duration_int,duration_type,Plataforma
0,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30,2014,G,113 min,"comedy, drama",a small fishing village must procure a local d...,99,as1,113,min,amazon
1,s2,movie,take care good night,girish joshi,"mahesh manjrekar, abhay mahajan, sachin khedekar",india,2021-03-30,2018,13+,110 min,"drama, international",a metro family decides to fight a cyber crimin...,37,as2,110,min,amazon
2,s3,movie,secrets of deception,josh webber,"tom sizemore, lorenzo lamas, robert lasardo, r...",united states,2021-03-30,2017,G,74 min,"action, drama, suspense",after a man discovers his wife is cheating on ...,20,as3,74,min,amazon
3,s4,movie,pink: staying true,sonia anderson,"interviews with: pink, adele, beyoncé, britney...",united states,2021-03-30,2014,G,69 min,documentary,"pink breaks the mold once again, bringing her ...",27,as4,69,min,amazon
4,s5,movie,monster maker,giles foster,"harry dean stanton, kieran o'brien, george cos...",united kingdom,2021-03-30,1989,G,45 min,"drama, fantasy",teenage matt banting wants to work with a famo...,75,as5,45,min,amazon
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3068,s3069,tv show,star trek: the original series,NaN,NaN,united states,NaT,1966,TV-PG,3 Seasons,"action, adventure, classics",the 23rd century adventures of captain james t...,14,hs3069,3,Seasons,hulu
3069,s3070,tv show,star trek: voyager,NaN,NaN,united states,NaT,1997,TV-PG,7 Seasons,"action, adventure, science fiction",catapulted into the distant sector of the gala...,53,hs3070,7,Seasons,hulu
3070,s3071,tv show,the fades,NaN,NaN,united kingdom,NaT,2011,TV-14,1 Season,"horror, international, science fiction",seventeen-year-old paul is haunted by apocalyp...,81,hs3071,1,Season,hulu
3071,s3072,tv show,the twilight zone,NaN,NaN,united states,NaT,1959,TV-PG,5 Seasons,"classics, science fiction, thriller",rod serling's seminal anthology series focused...,81,hs3072,5,Seasons,hulu
3072,s3073,tv show,tokyo magnitude 8.0,NaN,NaN,japan,NaT,2009,TV-14,1 Season,"anime, drama, international",the devastation is unleashed in the span of se...,47,hs3073,1,Season,hulu

Cantidad de veces que aparece una keyword en el título de peliculas/series, por plataforma

In [ ]:
def CountKey(plataforma, Keyword):
    #bases_datos.loc["Plataforma"]
    db_b = bases_datos[bases_datos.Plataforma == plataforma]
    db_b = db_b[db_b.title == Keyword]
    Numero = len(db_b)
    print (Numero)
    return Numero

In [34]:
def Get_Second_Score(plataforma):    
    db_b1 = bases_datos[(bases_datos.Plataforma == plataforma) & (bases_datos.type == "movie")]
    #db_b1 = bases_datos[]
    db_b2 = db_b1.sort_values('score', ascending=False)    
    
    #print(db_b2.iloc[0].score)
    try:
        db_b2 = db_b2[db_b2.score == db_b2.iloc[1].score]
    except:
        print("La plataforma de busqueda no fue encontrada¡¡")
        return "Error"
    db_b2 = db_b2.sort_values(by = 'title', ascending=True)
    #print(db_b2)
    #print(db_b2)
    try: 
        pelicula2 = db_b2.iloc[1].title
    except: 
        pelicula2 = db_b2.iloc[0].title
    scoreM = db_b2.iloc[0].score
    #print(pelicula2, "score: ", db_b2.iloc[0].score)
    return pelicula2, scoreM

Cantidad de series y películas por rating

In [35]:
def longest(plataforma, duration_type, year):
    db_b = bases_datos[bases_datos.Plataforma == plataforma]
    db_b1 = db_b[db_b.duration_type == duration_type]
    db_b2 = db_b1[db_b1.release_year == year].reset_index()
    db_b2.duration_int = db_b2.duration_int.astype(int)
    #db_b2.convert_dtypes(convert_string=False)
    #print(db_b2)
    db3 = db_b2.sort_values(by = 'duration_int', ascending=False)
    #for i in db3.duration_int:
        #print(i, type(i))
    #print(db3)
    peliculaMax = db3.iloc[0].title
    #print(max(db_b2.duration_int))
    #print(d)
    #db_b2[db_b2.duration_int.max()], db_b2[db_b2["duration_type"]]
    return peliculaMax, db3.iloc[0].duration_int
longest("netflix", "min", 2016)

('sairat', 173)

Cantidad de series y películas por rating

In [ ]:
def rating_count(rating):
    db_b = bases_datos[bases_datos.rating == rating]
    Numero = len(db_b)
    print ("rating: ",rating, "cantidad: ",Numero)
    return Numero
rating_count("18+")

rating:  18+ cantidad:  1243

1243

Cantidad de películas por plataforma con un puntaje mayor a XX en determinado año

In [ ]:
def score_count (plataforma, score, year):
    db_b = bases_datos[bases_datos.Plataforma == plataforma]
    db_b1 = db_b[db_b.release_year == year]
    db_b2 = db_b1[db_b1.score == score]
    Numero = len(db_b2)
    print("plataforma: ",plataforma, "cantidad: ", Numero)

score_count("netflix", 85, 2010)

plataforma:  netflix cantidad:  1

FastAPI

In [ ]:
from fastapi import FastAPI, Form
app = FastAPI(title="Proyecto Data Engiennering")

app = FastAPI()

@app.get('/')
async def root():
    return "Hello, listo pa probar esta poderosa api?"

def crearBases():
    amazon_prime_tittles = pd.read_csv("amazon_prime_titles-score.csv")

    amazon_prime_tittles["id"] = "a" + amazon_prime_tittles["show_id"]
    amazon_prime_tittles["rating"].fillna("G", inplace = True)

    amazon_prime_tittles["type"] = amazon_prime_tittles["type"].str.lower()
    amazon_prime_tittles["title"] = amazon_prime_tittles["title"].str.lower()
    amazon_prime_tittles["director"] = amazon_prime_tittles["director"].str.lower()
    amazon_prime_tittles["cast"] = amazon_prime_tittles["cast"].str.lower()
    amazon_prime_tittles["country"] = amazon_prime_tittles["country"].str.lower()
    amazon_prime_tittles["date_added"] = amazon_prime_tittles["date_added"].str.lower()
    amazon_prime_tittles["listed_in"] = amazon_prime_tittles["listed_in"].str.lower()
    amazon_prime_tittles["description"] = amazon_prime_tittles["description"].str.lower()

    name=amazon_prime_tittles["duration"].str.split(expand=True)
    name.columns=["duration_int", "duration_type"]
    amazon_prime_tittles=pd.concat([amazon_prime_tittles, name], axis=1)

    amazon_prime_tittles.drop(["duration"], axis=1)

    amazon_prime_tittles["date_added"] = pd.to_datetime(amazon_prime_tittles["date_added"])
    amazon_prime_tittles["Plataforma"] = "amazon"
    amazon_prime_tittles["release_year"].min()

    #amazon_prime_tittles.head()
    print(amazon_prime_tittles)


    disney_plus_titles = pd.read_csv("disney_plus_titles-score.csv")

    disney_plus_titles["id"] = "d" + disney_plus_titles["show_id"]
    disney_plus_titles["rating"].fillna("G", inplace = True)

    disney_plus_titles["type"] = disney_plus_titles["type"].str.lower()
    disney_plus_titles["title"] = disney_plus_titles["title"].str.lower()
    disney_plus_titles["director"] = disney_plus_titles["director"].str.lower()
    disney_plus_titles["cast"] = disney_plus_titles["cast"].str.lower()
    disney_plus_titles["country"] = disney_plus_titles["country"].str.lower()
    disney_plus_titles["date_added"] = disney_plus_titles["date_added"].str.lower()
    disney_plus_titles["listed_in"] = disney_plus_titles["listed_in"].str.lower()
    disney_plus_titles["description"] = disney_plus_titles["description"].str.lower()

    name=disney_plus_titles["duration"].str.split(expand=True)
    name.columns=["duration_int", "duration_type"]
    disney_plus_titles=pd.concat([disney_plus_titles, name], axis=1)

    disney_plus_titles.drop(["duration"], axis=1)

    disney_plus_titles["date_added"] = pd.to_datetime(disney_plus_titles["date_added"])
    disney_plus_titles["Plataforma"] = "disney"
    disney_plus_titles["release_year"].min()

    disney_plus_titles.head()
    print(disney_plus_titles)


    netflix_titles =pd.read_csv("netflix_titles-score.csv")
    netflix_titles["id"] = "a" + netflix_titles["show_id"]
    netflix_titles["rating"].fillna("G", inplace = True)

    netflix_titles["type"] = netflix_titles["type"].str.lower()
    netflix_titles["title"] = netflix_titles["title"].str.lower()
    netflix_titles["director"] = netflix_titles["director"].str.lower()
    netflix_titles["cast"] = netflix_titles["cast"].str.lower()
    netflix_titles["country"] = netflix_titles["country"].str.lower()
    netflix_titles["date_added"] = netflix_titles["date_added"].str.lower()
    netflix_titles["listed_in"] = netflix_titles["listed_in"].str.lower()
    netflix_titles["description"] = netflix_titles["description"].str.lower()

    name=netflix_titles["duration"].str.split(expand=True)
    name.columns=["duration_int", "duration_type"]
    netflix_titles=pd.concat([netflix_titles, name], axis=1)
    netflix_titles.drop(["duration"], axis=1)
    netflix_titles["date_added"] = pd.to_datetime(netflix_titles["date_added"])
    netflix_titles["Plataforma"] = "netflix"
    netflix_titles.head()

    hulu_titles = pd.read_csv("hulu_titles-score (2).csv")

    hulu_titles["id"] = "h" + hulu_titles["show_id"]
    hulu_titles["rating"].fillna("G", inplace = True)
    hulu_titles["type"] = hulu_titles["type"].str.lower()
    hulu_titles["title"] = hulu_titles["title"].str.lower()
    hulu_titles["director"] = hulu_titles["director"].str.lower()
    #hulu_titles["cast"].str.lower()
    hulu_titles["country"] = hulu_titles["country"].str.lower()
    hulu_titles["date_added"] = hulu_titles["date_added"].str.lower()
    hulu_titles["listed_in"] = hulu_titles["listed_in"].str.lower()
    hulu_titles["description"] = hulu_titles["description"].str.lower()

    name= hulu_titles["duration"].str.split(expand=True)
    name.columns=["duration_int", "duration_type"]
    hulu_titles=pd.concat([hulu_titles, name], axis=1)
    hulu_titles.drop(["duration"], axis=1)

    hulu_titles["date_added"] = pd.to_datetime(hulu_titles["date_added"])
    hulu_titles["Plataforma"] = "hulu"


    bases_datos = pd.concat([amazon_prime_tittles, disney_plus_titles, netflix_titles, hulu_titles])
    #bases_datos

    return bases_datos
bases_datos = crearBases()

#Cantidad de veces que aparece una keyword en el título de peliculas/series, por plataforma
#@app.route('/CountKey', methods=["GET"])
@app.post("/CountKey")
async def login(plataforma: str = Form(), Keyword: str = Form()):
#def CountKey():
    #plataforma = request.form.get('plataforma')
    #Keyword = request.form.get('Keyword')
    print (plataforma) #, Keyword)
    #bases_datos.loc["Plataforma"]
    '''
    db_b = bases_datos[bases_datos.Plataforma == plataforma]
    db_b = db_b.loc[[True if Keyword in title else False for title in db_b["title"]]]
    #print (db_b)    
    Numero = len(db_b)
    '''
    Numero = "mrd"
    #print (Numero)
    return {
        "plataforma": plataforma,
        "Keywords": Keyword
    }
    #return Numero
#CountKey("netflix", "love")


#Cantidad de películas por plataforma con un puntaje mayor a XX en determinado año
@app.get('/score_count')
async def score_count():
#def score_count (plataforma, score, year):
    plataforma = "netflix"
    year = 2010
    score = 85

    db_b = bases_datos[bases_datos.Plataforma == plataforma]
    db_b1 = db_b[db_b.release_year == year]
    db_b2 = db_b1[db_b1.score > score]
    Numero = len(db_b2)
    print("plataforma: ",plataforma, "cantidad: ", Numero)
    return Numero
#score_count("netflix", 85, 2010)

@app.get('/Get_Second_Score')
def Get_Second_Score(plataforma):   
    db_b1 = bases_datos[(bases_datos.Plataforma == plataforma) & (bases_datos.type == "movie")]
    #db_b1 = bases_datos[]
    db_b2 = db_b1.sort_values('score', ascending=False) 
    
    #print(db_b2.iloc[0].score)
    try:
        db_b2 = db_b2[db_b2.score == db_b2.iloc[1].score]
    except:
        print("La plataforma de busqueda no fue encontrada¡¡")
        return "Error"
    db_b2 = db_b2.sort_values(by = 'title', ascending=True)
    #print(db_b2)
    #print(db_b2)
    try: 
        pelicula2 = db_b2.iloc[1].title
    except: 
        pelicula2 = db_b2.iloc[0].title
    scoreM = db_b2.iloc[0].score
    #print(pelicula2, "score: ", db_b2.iloc[0].score)
    return pelicula2 #, scoreM
#Get_Second_Score("amazon")


#Cantidad de series y películas por rating
@app.get('/longest')
def longest(plataforma, duration_type, year):
    db_b = bases_datos[bases_datos.Plataforma == plataforma]
    db_b1 = db_b[db_b.duration_type == duration_type]
    db_b2 = db_b1[db_b1.release_year == year].reset_index()
    db_b2.duration_int = db_b2.duration_int.astype(int)
    #db_b2.convert_dtypes(convert_string=False)
    #print(db_b2)
    db3 = db_b2.sort_values(by = 'duration_int', ascending=False)
    #for i in db3.duration_int:
        #print(i, type(i))
    #print(db3)
    peliculaMax = db3.iloc[0].title
    #print(max(db_b2.duration_int))
    #print(d)
    #db_b2[db_b2.duration_int.max()], db_b2[db_b2["duration_type"]]
    return peliculaMax #, db3.iloc[0].duration_int
#longest("netflix", "min", 2016)

@app.get('/rating_count')
def rating_count(rating):
    db_b = bases_datos[bases_datos.rating == rating]
    Numero = len(db_b)
    print ("rating: ",rating, "\ncantidad: ",Numero)
    return Numero
#rating_count("18+")